title: PRADEEP.md
description: notes and code
url: https://pradeep.md
author: pradeep elankumaran
twitter: pradeep24
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true

unpublished: true
