title: pradeep elankumaran
description: notes and code
url: https://skyfallsin.github.io
author: pradeep elankumaran
twitter: pradeep24
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true
