title: PRADEEP.md
description: notes and code
url: https://pradeep.md
author: pradeep elankumaran
twitter: pradeep24
markdown: kramdown

plugins:
  - jekyll-feed

feed:
  path: feed.xml

kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true

unpublished: true
